### ISSUE TITLE
upload images

### ISSUE THREAD

**Issue by SamPom100** [SamPom100/UnusualVolumeDetector#1]
![s9jtygygl0e51](https://user-images.githubusercontent.com/28206070/88943801-8c860a00-d251-11ea-833b-8e7685360ab2.png)
![ue395lbgl0e51](https://user-images.githubusercontent.com/28206070/88943804-8d1ea080-d251-11ea-8c03-3f42da8849f6.png)
![j67nuj3cl0e51](https://user-images.githubusercontent.com/28206070/88943805-8d1ea080-d251-11ea-81ed-04138e21bf1f.png)

![logo](https://user-images.githubusercontent.com/28206070/89098977-b6eed900-d3b1-11ea-82c4-2151f0a54bfc.jpg)

**Comment by SamPom100** [comment]
<img width="1347" alt="Screen Shot 2020-08-01 at 3 24 03 AM" src="https://user-images.githubusercontent.com/28206070/89097652-7ccc0a00-d3a6-11ea-949d-234a6517772c.png">

**Comment by Stjernex24** [comment]
Many thanks. Have you thought of combining this with OBV indicator or even
better a script that I can insert onto the graph called Volume flow
indicator by lazy bear. Script orinally used by million dollar trader.
Reason? Could help predict tops and bottoms on volume.

**Comment by Stjernex24** [comment]
Volume flow indicator or VFI_LF can be found free on Tradingview can you
please tell me how to add it on the graph? Where it shows volume spiking...
Really new to scripts.

**Comment by Jacklynzack** [comment]
@tcosculluela
