### ISSUE TITLE
Time to load > 5 min

### ISSUE THREAD

**Issue by blockbat** [SamPom100/UnusualVolumeDetector#10]
Is this thing taking forever to load for anyone else?

**Comment by luisott** [comment]
> Is this thing taking forever to load for anyone else?

It takes over 30 minutes to run, do you see a progress indicator? If so it is running, it's going through 9k tickers so makes sense that takes a long time. I wonder if we can reduce the list to let's say only include tickers with float under 20M and maybe price under $5

**Comment by jameswolensky** [comment]
I added a pull request to remove ETFs from the results. Takes away ~2000 tickers from the scan to speed it up. https://github.com/SamPom100/UnusualVolumeDetector/pull/14

**Comment by RKosow** [comment]
It might be worth caching the data somehow, so subsequent scans only look for the latest data.

**Comment by luisott** [comment]
I like the idea of only running this for tickers with low float (<20M) and stock price less than $10. I can't see any runners outside this range and that will give us 1k tickers max?
