### ISSUE TITLE
tqdm not found

### ISSUE THREAD

**Issue by jamaljones31415** [SamPom100/UnusualVolumeDetector#13]
ModuleNotFoundError: No module named 'tqdm'

**Comment by StevenAdema** [comment]
You need to install tqdm module, you can do it by using python pip.

`pip install tqdm`

**Comment by cerealturk** [comment]
I had use the command
python -m pip install tqdm

But I think it's just because my PATH doesn't include the pip directory. Also -m tells it to specifically install the module of the package.

**Comment by Stjernex24** [comment]
Hi I'm in south America and couldn't find the one you mentioned on
playstore. I am using pydroid3 would it work on mobile? If so how do you
input script onto pydroid3?
