### ISSUE TITLE
Cleanups

### ISSUE THREAD

**Issue by elizabethshirley** [SamPom100/UnusualVolumeDetector#17]
Kind of treating this issue ticket as a PR/MR
- Remove `find_anomalies` and rename `find_anomalies_two` to `find_anomalies` 
- Instead of the for-loops + append, you might be better served with a list comprehension or a generator. I'm going to try this on my machine, and I'll let you know what I find

**Comment by rbrasco** [comment]
- Using csv files instead of txt data

**Comment by SamPom100** [comment]
I'll work on this
