### ISSUE TITLE
Exclude large float tickers

### ISSUE THREAD

**Issue by luisott** [SamPom100/UnusualVolumeDetector#19]
Is this tool only useful for  low float tickers (less than 20M)? If so should we have an exclude_tickers.txt list to have all large float tickers that can be excluded? That way we could have 1k tickers to go through instead of 9k. Considerably saving time. I can work on adding the code to exclude tickers from a file but I don't have a complete list or a way to get them

**Comment by SamPom100** [comment]
I'll add this feature
