### ISSUE TITLE
Didn't print anything

### ISSUE THREAD

**Issue by ChiragJhawar** [SamPom100/UnusualVolumeDetector#23]
I ran the marketscanner.py but it didn't print anything except the time it took

**Comment by Connor9994** [comment]
Without any potential errors/logs, it would be impossible to say why your script isn't working. Likely an issue with a pre-req package not executing (or not existing).

**Comment by ChiragJhawar** [comment]
I did install all the requirements, it did not give me any errors but it did not give me any stocks either. Just printed the time it took to complete.

**Comment by Connor9994** [comment]
What parameters did you use for the time frame/standard deviation/etc? It's possible you just didn't find any stocks that matched your conditions.

**Comment by ChiragJhawar** [comment]
Honestly, I just ran it as it came to test it. But now I am running with a message to show if no stock exists with given parameters, I'll keep you updated as it happens.

**Comment by Connor9994** [comment]
Interesting. Well, from stock, it should take 50+ minutes and have a running/loading bar displaying the current index of the ticker it's looking at. If nothing pops up except the run time, then the script is likely having issues in either of the following function blocks. 

getData(self, ticker)
find_anomalies_two(self, data, cutoff)

**Comment by ChiragJhawar** [comment]
It is taking 50+ mins, Yeah, I'm trying to debug what the issue is. I am gonna play around with the numbers a little too, to see if it goes faster.

**Comment by Connor9994** [comment]
Turn on debugging if you're running in an IDE and see what the script is even executing. Would be curious why it doesn't even get to the custom print function.

**Comment by elizabethshirley** [comment]
The script as is doesn't pause at the end, and until yesterday noon EDT, most anomalies occurred in tickers 4-6k. If you leave the script alone, and come back after it's finished, then you wouldn't see anything
