### ISSUE TITLE
Forecasting Add On

### ISSUE THREAD

**Issue by cerealturk** [SamPom100/UnusualVolumeDetector#28]
Hey! No issue. I'm trying to add the functionality to compute a forecasting projection of any anomalous stocks found. 

I plan on using scikit-learn for the all the decision making algos. Currently, I am having an issue that the target array isn't in the right classification type. I'll add a screenshot of the error soon. Might see if weka provides a python library as an alternative to scikit-learn. 

If anyone would be interesting in collaborating, let me know!

**Comment by uzakov** [comment]
@cerealturk Create a fork for your functionality, so people can see

**Comment by SamPom100** [comment]
I'm looking forward to seeing your fork
