### ISSUE TITLE
Taking over 24 hrs to run for the first time

### ISSUE THREAD

**Issue by chsilva100685** [SamPom100/UnusualVolumeDetector#36]
Any idea why it could be taking over 24 hrs to execute for the first time?  I had no issues pip installing all the requirements. I tried to execute the code but it is painfully slow.  It did not error out, I ended the execution myself after I let it run for a day and it didn't finish.  I have a fast internet connection, connected via ethernet.
![UnusualVolume_slow](https://user-images.githubusercontent.com/69086969/89107027-9d6e8100-d3f3-11ea-9250-c085bd2ef513.JPG)

Thanks in advance for your help!

**Comment by elizabethshirley** [comment]
What sort of processor do you have?

**Comment by SamPom100** [comment]
are you running the latest version?

**Comment by elizabethshirley** [comment]
Also you're not getting very far, are you sure you're not being blocked by a firewall?
