### ISSUE TITLE
Increased speed on Intel when n_jobs is increased to 2x.

### ISSUE THREAD

**Issue by elizabethshirley** [SamPom100/UnusualVolumeDetector#42]
Specifically here:
`with parallel_backend('loky', n_jobs=multiprocessing.cpu_count()*2):`

Instead of 20-30 It/s as reported by TDQM, I'm seeing 40-50 It/s with spikes to 120it/s

I think this is because my connection is the bottleneck more than my processor, so I have 16 requests at a time waiting, and as they come in, my processor saturates. Do anyone else (Tyler), see this behavior?

**Comment by c0sc0** [comment]
Well I'll be! I'm getting double the CPU usage on my 4900HS (8c/16t) laptop, averaging 100-120it/s

Can push it even farther past that (up to 60 workers) but then my CPU grinds to a halt

I'm pretty sure yfinance supports a list of tickers as input, so we could probably split the tickerlist into batches of 4/8/whatever when getting data to mitigate the network bottleneck

**Comment by c0sc0** [comment]
pushed to #41 (with a warning mesage/comment)

curious to see how it handles with lower end CPUs
