### ISSUE TITLE
Off-by-one bug (tickers delayed by 1 day)

### ISSUE THREAD

**Issue by c0sc0** [SamPom100/UnusualVolumeDetector#44]
fixed in #41

when you give yfinance a range, it doesn't download the data for the enddate 
`data = yf.download(ticker, pastDate, currentDate)`

**Comment by SamPom100** [comment]
fixed by requesting tomorrow instead of today, thanks for pointing this out.

 currentDate = datetime.date.today() + datetime.timedelta(days=1)
