### ISSUE TITLE
market_scanner.py typo

### ISSUE THREAD

**Issue by pghorbani** [SamPom100/UnusualVolumeDetector#46]
line 30 should be MONTH_CUTTOFF instead of MONTH_CUTOFF as the variable, although the "CUTTOFF" is a typo itself

alternatively all the CUTTOFF variables should be renamed CUTOFF for spelling aesthetics

not sure if there's any technical problem with not calling that global

**Comment by c0sc0** [comment]
Haha, you're right on both parts, don't know how I missed that

It all works out in the end because the class is in the scope of the cutoffs (and we aren't writing to them)

Fixed (the scoping, not the typo :laughing: ) in #49

**Comment by SamPom100** [comment]
whoops, didn't even notice
