### ISSUE TITLE
Option to open link with another website like Yahoo Finance 

### ISSUE THREAD

**Issue by jeroensmink98** [SamPom100/UnusualVolumeDetector#47]
**Feature request**
It would be nice if there was some kind of slider/dropdown where the user can select if he want's to open the URL from the dashboard with another website for example Yahoo Finance or some other third party site. 

**Example url Yahoo Finance**
https://finance.yahoo.com/quote/TSLA?p=TSLA

![idea](https://user-images.githubusercontent.com/20206510/89382473-34d91a00-d6fb-11ea-90fd-1d235109907d.PNG)

**Comment by c0sc0** [comment]
Yeah that sounds easy enough! I just hardcoded the RH URLs in the template because I was lazy.

Just need to take the URL out and make it an empty link, then write a jquery onclick handler and have it read that input value
