### ISSUE TITLE
Scanning slows to a crawl

### ISSUE THREAD

**Issue by HaxOh** [SamPom100/UnusualVolumeDetector#48]
Running on an i7-6850K @ 3.6GHz

Scanning starts out really quickly getting up to around 20% within a minute. After that it starts slowing down a lot taking 10 minutes to get to 36%

**Comment by c0sc0** [comment]
I've found that the script is bottlenecked by the yfinance api calls more than anything, not much we could do about that except batch the calls.

You can try doubling the number of workers and see if that changes things
`with parallel_backend('loky', n_jobs=multiprocessing.cpu_count() * 2):`
