### ISSUE TITLE
Yfinance not found error

### ISSUE THREAD

**Issue by indygill** [SamPom100/UnusualVolumeDetector#6]
Install without any issues using `install -r requirements.txt`

When running `python market_scanner.py` I am met with the following error: 

`Traceback (most recent call last):
    File "market_scanner.py", line 3, in <module>
    import yfinance as yf
    ImportError: No module named yfinance`

Running `pip show yfinance` returns 
`Name: yfinance
Version: 0.1.54
Summary: Yahoo! Finance market data downloader
Home-page: https://github.com/ranaroussi/yfinance
Author: Ran Aroussi
Author-email: ran@aroussi.com
License: Apache
Location: /usr/local/lib/python3.6/site-packages
Requires: pandas, numpy, requests, multitasking`

**Comment by indygill** [comment]
> Install without any issues using `install -r requirements.txt`
> 
> When running `python market_scanner.py` I am met with the following error:
> 
> `Traceback (most recent call last): File "market_scanner.py", line 3, in <module> import yfinance as yf ImportError: No module named yfinance`
> 
> Running `pip show yfinance` returns
> `Name: yfinance Version: 0.1.54 Summary: Yahoo! Finance market data downloader Home-page: https://github.com/ranaroussi/yfinance Author: Ran Aroussi Author-email: ran@aroussi.com License: Apache Location: /usr/local/lib/python3.6/site-packages Requires: pandas, numpy, requests, multitasking`

**Comment by rohhenry** [comment]
What python version are you running?

**Comment by luisott** [comment]
> What python version are you running?

I think it has to be 3, so all commands for both python and pip run `python3` and `pip3`

**Comment by cerealturk** [comment]
I had to run the following command:

python3 -m pip install yfinance

The -m tells it to install the module.

I also hit a couple other modules that the requirements.txt file didn't cover. However the command above solved my issues!

**Comment by EEElizondo** [comment]
I use windows Visual Studio and can get the script to run market_scanner.py  is this script not  for windows ?. It can't find yfinance.

**Comment by cerealturk** [comment]
I'm using the anaconda terminal on windows and it worked fine

**Comment by indygill** [comment]
I should have pointed out that this was a fresh python install on CentOS 7

**Comment by indygill** [comment]
Got it working by using python3 instead of just python. Thanks @luisott for the suggestion.
